name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '40 3 * * *'
    # cron表达式，Actions时区是UTC时间，需要往前推8个小时  此时为6点30推送

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      run: |
        pip3 install requests
        python3 SignIn.py
      env:
        LUCK_DRAW: ${{ secrets.LUCK_DRAW }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        COOKIE: ${{ secrets.COOKIE }}
        REFERER: ${{ secrets.REFERER }}
